// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC72hzY8ryNf90ibQaE3VGPY3UUgOU1KmQ',
    appId: '1:905358406212:web:1d3a6dfc2a8d9de4e74211',
    messagingSenderId: '905358406212',
    projectId: 'news-ware-4b3d0',
    authDomain: 'news-ware-4b3d0.firebaseapp.com',
    databaseURL: 'https://news-ware-4b3d0-default-rtdb.firebaseio.com',
    storageBucket: 'news-ware-4b3d0.appspot.com',
    measurementId: 'G-B0NMY0T2H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu7uQOauVmrKWvwizqd12aik8UsAqYtqw',
    appId: '1:905358406212:android:33b303694adcbbcde74211',
    messagingSenderId: '905358406212',
    projectId: 'news-ware-4b3d0',
    databaseURL: 'https://news-ware-4b3d0-default-rtdb.firebaseio.com',
    storageBucket: 'news-ware-4b3d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4N-VAt9MOKxVHt_XsVJ0VJ--NMjvvFCY',
    appId: '1:905358406212:ios:56ffbdf419ff8838e74211',
    messagingSenderId: '905358406212',
    projectId: 'news-ware-4b3d0',
    databaseURL: 'https://news-ware-4b3d0-default-rtdb.firebaseio.com',
    storageBucket: 'news-ware-4b3d0.appspot.com',
    androidClientId: '905358406212-k0otcm0oi4oj1im9kfb7ppa5gg2poibh.apps.googleusercontent.com',
    iosClientId: '905358406212-t1ol6ajbtmduap4f0phr59rc45ldc2jg.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsWare',
  );
}
